spring:
  profiles:
    active: qa

build: 
  version: 2.0.0

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "QA Sam  - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (666) 555-1234

    - (666) 523-1345
